const permission_config = {
  CustomerCard: "CUSTO000",
  CustomerPartySearch: "CUSTO001",
  CustomerDetailsScreen: "CUSTO002",
  OutstandingCard: "OUTST000",
  OutstandingDashboardScreen: "OUTST001",
  PartySearchScreen: "OUTST002",
  PartyBillDetailScreen: "OUTST003",
  AgingOutstandingCard: "OUTST004",
  BrokerAgingCard: "VBROK000",
  BrokerAgingOverview: "VBROK001",
  BrokerBillDetails: "VBROK002",
  SalesPurchaseCard: "VOUCH000",
  VoucherOverviewScreen: "VOUCH001",
  VoucherDetailScreen: "VOUCH002",
  InventoryCard: "INVEN000",
  InventoryOverviewScreen: "INVEN001",
  ItemDetailScreen: "INVEN002",
  InventoryDetailScreen: "INVEN003",
  BrokerSchemeLeaderBoardOverview: "VBROK011",
  BrokerSchemeDetails: "VBROK012",
  MasterConfigButton: "CNF0001",
  FeatureConfigButton: "CNF0002",
  ExecutiveSaleButton: "CNF0003",
  ExecutiveAgingButton: "CNF0004",
  CollectionReportButton: "CNF0005",
  OrderSummaryReportButton: "CNF0006",
  IndividualSalesReportButton: "CNF0007",
  SalesReportCard: "CNF0008",



  UserPermissions: "TRAN000",
  ItemGroupCard :"TRAN001",
  BillsCard : "TRAN002",
  MonthlySalesCard :"TRAN003",
  MonthlyCustomerSalesCard :"TRAN004",
  MovementConfig : "TRAN005",
  AgingSettings : "TRAN006",


  BrokerOutstandingCard: "BBROK000",
  BrokerOutstandingDashboardScreen: "BBROK001",
  BrokerPartySearchScreen: "BBROK002",
  BrokerPartyBillDetailScreen: "BBROK003",
  BrokerAgingOutstandingCard: "BBROK004",
  DashboardCommisionCard: "BCOMM001",
  BrokerComissionPartySearch: "BCOMM001",
  BrokerComissionPartyBillDetail: "BCOMM002",
  BrokerSchemeOverview: "BSCHE000",
  BrokerSchemeOverviewDetails: "BSCHE001",
};

export default permission_config;
