import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Softgen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full pr-2 bg-gray-50 ${inter.className} overflow-x-hidden`}>{children}</body>
    </html>
  );
}
